# Generated by Django 5.1.2 on 2025-04-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasktitle', models.CharField(max_length=30)),
                ('taskdesc', models.TextField()),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
